### ISSUE TITLE
Find alternative method to generate swagger ui and openapi specs

### ISSUE THREAD

**Issue by slavistan** [bird-wp07/local-module#11]
Find alternative method to generate swagger ui and openapi specs.

tsoa
- Can't generate example requests with decorators (#1107)
- Doesn't recognize globally defined types
- Generated swagger ui displays unions of enums and literal strings incorrectly
- Can't annotate examples
- Can't modify generated express boilerplate; di is cumbersome
- Issues auto-close after 30 days of inactivity; non-trivial bugs never get evaluated or fixed
- subtle, almost impossible to find bug:
```
// src/server/controllers/types.ts
import { EDigestAlgorithm } from "../../dss"
export interface IDigestBlobRequest {
    bytes: Base64
    digestAlgorithm: EDigestAlgorithm
}
```
vs.
```
// src/server/controllers/types.ts
import * as Dss from "../../dss"
export interface IDigestBlobRequest {
    bytes: Base64
    digestAlgorithm: Dss.EDigestAlgorithm // <-- breaks validation and ruins the http interface completely
} 
```

**Comment by stnmtz** [comment]
@slavistan Dieser hier kann doch geschlossen werden?
