### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by FPfotenhauer** [bird-wp07/local-module#12]
Version 0.0.22
Linux Standalone x64 
Ubuntu 22.04

```
AxiosError: Request failed with status code 500
    at settle (/home/pfotenhauer/bird-wp07/wp07-local-module-linux-x64-standalone-v0.0.22/local-module/node_modules/axios/dist/node/axios.cjs:1268:12)
    at IncomingMessage.handleStreamEnd (/home/pfotenhauer/bird-wp07/wp07-local-module-linux-x64-standalone-v0.0.22/local-module/node_modules/axios/dist/node/axios.cjs:2446:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
When POST any String to
http://localhost:2048/swagger/#/default/ValidateSignedPdf

**Comment by FPfotenhauer** [comment]
Gibt es die Version 0.0.27 auch als Standalone Win/Linux?
Da scheint etwas mit den Build-Scripten für die Releases nicht in Ordnung zu sein.

**Comment by slavistan** [comment]
@FPfotenhauer ich schaue rein und löse die Builds gleich nochmal aus.

**Comment by FPfotenhauer** [comment]
Danke.
Gibt es die Standalone-Versionen nicht mehr?

**Comment by slavistan** [comment]
Doch, gibt es. Da dauert der Bau des Pakets nur lange.

Ich hab das Problem behoben und melde mich im Anschluss an den Upload der Pakete.

**Comment by slavistan** [comment]
@FPfotenhauer alle Bundles sind online (Version 0.0.30).

In den Archiven befindet sich auch eine Postman Collection *postman.json* mit Beispielaufrufen. Ich nicht sicher, ob dies in vergangenen Meetings kommuniziert worden ist.

**Comment by FPfotenhauer** [comment]
Ok. Danke.
Wenn ich jetzt die Beispiele aus der Postman-Collection nehme, bekomme ich eine richtige response.
Wenn ich aber einfach irgendwas ungültiges übergebe "kdjfhgsakgf", gibt es noch den 500 internal server error.

**Comment by slavistan** [comment]
Es sind bisher lediglich die Happy Paths ausimplementiert. Systematisches Fehlerhandling ist gerade in Arbeit und die angezeigten Fehler sind daher noch kryptisch.

**Comment by FPfotenhauer** [comment]
OK, danke. Dann schließe ich das Issue.
