### ISSUE TITLE
Test-Release startet nicht

### ISSUE THREAD

**Issue by FPfotenhauer** [bird-wp07/local-module#38]
Unter Windows startet der Server, aber die Swagger ist nicht ereichbar:

![SNAG_2023_02_15_12 44 59](https://user-images.githubusercontent.com/34127980/219018845-f6d12022-ff39-403a-bf3d-5daf2e21a9d3.png)

Unter Linux Debian 11 startet der Server gar nicht:

![SNAG_2023_02_15_12 46 37](https://user-images.githubusercontent.com/34127980/219019052-c19016ff-4a9f-4386-a1f4-3886b3c6f94d.png)

**Comment by FPfotenhauer** [comment]
Auch das neue Release startet, weder unter Windows noch unter Linux bei mir.
Das die SwaggerUi nicht funktioniert hat man mir mittlerweile gesagt.

**Comment by slavistan** [comment]
@FPotenhauer Die Test-Releases dienen dem internen Testen. Wenn alles nach Plan läuft erhalten Sie morgen das nächste lauffähige Release, wiederum mit vollständiger Swagger API Spielwiese und Dokumentation.

**Comment by slavistan** [comment]
@FPfotenhauer das Linux `start.sh` Skript braucht das `jq` Programm zum Parsen von JSON. Ist der de-facto Standard auf Linuxsystemen, aber nicht auf jedem System standardmäßig vorhanden. Ist es im Allgemeinen möglich das via dem Paketmanager nachzuinstalieren?

**Comment by FPfotenhauer** [comment]
> @FPfotenhauer das Linux `start.sh` Skript braucht das `jq` Programm zum Parsen von JSON. Ist der de-facto Standard auf Linuxsystemen, aber nicht auf jedem System standardmäßig vorhanden. Ist es im Allgemeinen möglich das via dem Paketmanager nachzuinstalieren?

Probiere ich aus. Das mit den test-releases wusste ich nicht. Ich néhme dann nur noch die anderen...
