### ISSUE TITLE
merge XML

### ISSUE THREAD

**Issue by FPfotenhauer** [bird-wp07/local-module#41]
Wäre es möglich in der API noch einen Endpunkt zu schaffen, der das XML mit dem PDF verbindet?
Ich fände es sinnvoll, wenn alle Prozesse von dem local-module ausgeführt werden könnten.

**Comment by slavistan** [comment]
@FPfotenhauer Geht es um das Einbetten von XSchule XML Dateien ins (noch unsignierte) PDF Zeugnis? Das ist möglich.

**Comment by stnmtz** [comment]
Benötigen wir dies für den Feldtest? Wir hatten eigentlich für den Feldtest bisher nur den umgekehrten Weg (aus einem signierten Zeugnis die möglichen existierenden Attachments herausziehen) angedacht.

**Comment by FPfotenhauer** [comment]
@slavistan ist das der Endpunkt "/merge/pdf" ?

@stnmtz Nein, für den Feldtest nicht, aber ich würde gerne alle Schritte mit Postman durchführen können. Dann kann ich das besser an meine Leute geben, wenn wir das im SVWS-Server benötigen. Wir probieren hier gerade mit "zentralen lokal-modul" für Installationsumgebungen mit mehreren Schulen bei einem Schulträger....

**Comment by stnmtz** [comment]
Ich glaube @slavistan meinte eher, dass wir das entsprechend implementieren könnten ;)

**Comment by FPfotenhauer** [comment]
Dann wäre das super. Ich wäre dann unabhängig vom Delphi-ZSM.

**Comment by stnmtz** [comment]
> Nein, für den Feldtest nicht, aber ich würde gerne alle Schritte mit Postman durchführen können. Dann kann ich das besser an meine Leute geben, wenn wir das im SVWS-Server benötigen. Wir probieren hier gerade mit "zentralen lokal-modul" für Installationsumgebungen mit mehreren Schulen bei einem Schulträger....

Verstanden, ich würde die Feldtest-relevanten Dinge erstmal priorisieren - wobei es da ja mit dem aktuellen Release sehr gut aussieht. Ich denke das Extrahieren und Anhängen wäre beides nicht wirklich problematisch, aber der Teufel steckt da wohl wie immer im Detail ;) Wobei das Extrahieren (für die Hochschulen) wohl wichtiger ist, als das Anhängen.

**Comment by stnmtz** [comment]
@FPfotenhauer nur als Randnotiz: Der Ablauf funktioniert auch ohne PDF Attachments, also die komplette Implementierung benötigt bisher keine PDF Attachments.

**Comment by slavistan** [comment]
Landet im nächsten Release v0.2.6.
