### ISSUE TITLE
jq nachinstallieren

### ISSUE THREAD

**Issue by FPfotenhauer** [bird-wp07/local-module#42]
Wenn man unter Debian11 das ./start.sh ausführt und dann merkt, dass jq noch nicht installiert ist, dann existiert der Ordner DSS schon.
Beim nächsten Start schlägt das fehl, weil der DSS-Download nicht startet. Man muss dann verstehen, dass man den DSS-Ordner vorher löschen muss.

**Comment by slavistan** [comment]
@FPfotenhauer Ja, ist bekannt. Das habe ich versucht im Absatz 2.3.4 unterzubringen.

>Bei einem Fehler während der Initialisierung aufgrund fehlender Programme empfehlen wir den gesamten Prozess in einem leeren Verzeichnis erneut durchzuführen.

Man könnte aber beim Ausführen der start.sh einfach alle Abhängigkeiten checken - kommt ins nächste Release. Ich nutze dieses Ticket als Erinnerung.

**Comment by slavistan** [comment]
Landet im nächsten Release v0.2.6.
